export enum StreamEvents {
  ADD = 'STREAM.ADD',
  REMOVE = 'STREAM.REMOVE',
}

export enum StreamMessages {
  UPDATE_TITLE = 'STREAM.UPDATE_TITLE',
  ERRORS = 'STREAM.ERRORS',
  JOIN_ROOM = 'STREAM.JOIN_ROOM',
  ROOM_MESSAGE = 'STREAM.ROOM_MESSAGE',
  LEAVE_ROOM = 'STREAM.LEAVE_ROOM',
}
